<?php

declare(strict_types=1);

namespace App\Modules\AI\DTO;

/**
 * DTO holding the raw JSON SOAP note draft generated by Gemini.
 *
 * This DTO is intentionally generic because the exact SOAP schema may evolve.
 */
final class SoapDraftDTO
{
    /**
     * @param array<string,mixed> $raw
     */
    public function __construct(public readonly array $raw) {}


    /**
     * @param array<string,mixed> $data
     * @return self
     */
    public static function fromArray(array $data): self
    {
        return new self($data);
    }

    /**
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        return $this->raw;
    }
}


